spring:
  application:
    name: ordersms
  datasource:
    url: jdbc:mysql://localhost:3306/oms_dev?createDatabaseIfNotExist=true
    username: root
    password:
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false
  jpa:
    show-sql: true